# Generated by Django 4.2.4 on 2023-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='performance',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
