# Generated by Django 4.2.4 on 2023-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_ticket_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performance',
            field=models.CharField(max_length=50),
        ),
    ]
