# Generated by Django 4.2.4 on 2023-09-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_ticket_memo_alter_ticket_id_alter_ticket_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='memo',
            new_name='ticket_memo',
        ),
    ]
