# Generated by Django 4.2.4 on 2023-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_rename_memo_ticket_ticket_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=200)),
            ],
        ),
    ]
