# Generated by Django 4.2.4 on 2023-09-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_remove_ticket_ticket_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='writer',
        ),
    ]
