# Generated by Django 4.2.5 on 2023-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0009_ticketmemo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_memo",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="TicketMemo",
        ),
    ]
