# Generated by Django 4.2.4 on 2023-09-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_compost_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('compost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comcomments', to='community.compost')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ComReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comcomment')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ComPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, null=True, upload_to='compost_media/')),
                ('compost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.compost')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('heart', 'Heart')], max_length=10)),
                ('compost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.compost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
