# Generated by Django 4.2.4 on 2023-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comcomment_comreply_compostmedia_communityreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='compost',
            name='comcomments_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
