# Generated by Django 4.2.4 on 2023-09-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_compost_comcomments_cnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComPostMedia',
        ),
    ]
