# Generated by Django 4.2.4 on 2023-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_delete_compostmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='compost',
            name='category',
            field=models.CharField(choices=[('자유게시판', '자유게시판'), ('질문게시판', '질문게시판')], default='', max_length=10),
        ),
    ]
