# Generated by Django 4.2.4 on 2023-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_compost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compost',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('질문', '질문'), ('에디터 픽', '에디터 픽')], default='', max_length=10),
        ),
    ]
