# Generated by Django 4.2.5 on 2023-09-14 19:07

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0018_alter_compost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=community.models.image_upload_path
            ),
        ),
    ]
