# Generated by Django 4.2.4 on 2023-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=10000)),
                ('reviews_cnt', models.PositiveIntegerField(default=0)),
                ('genre_type', models.CharField(choices=[('뮤지컬', '뮤지컬'), ('연극', '연극'), ('클래식', '클래식'), ('무용', '무용'), ('콘서트', '콘서트'), ('아동/가족', '아동/가족')], default='뮤지컬', max_length=10)),
                ('location', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('충청', '충청'), ('경상', '경상'), ('전라', '전라'), ('제주', '제주')], default='서울', max_length=10)),
            ],
        ),
    ]
