# Generated by Django 4.2.4 on 2023-09-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_mainpost_content_mainreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='mainreview',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mainreviews', to='mypage.ticket'),
        ),
        migrations.AlterField(
            model_name='mainreview',
            name='mainpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainreviews', to='main.mainpost'),
        ),
        migrations.CreateModel(
            name='MainReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('공감', '공감'), ('heart', 'Heart')], max_length=10)),
                ('mainreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.mainreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainReviewComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mainreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainrecoms', to='main.mainreview')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
