# Generated by Django 4.2.4 on 2023-09-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_mainreview_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpost',
            old_name='genre_type',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='mainpost',
            old_name='reviews_cnt',
            new_name='mainreviews_cnt',
        ),
        migrations.AddField(
            model_name='mainreview',
            name='mainrecoms_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MainPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'like'), ('heart', 'Heart')], max_length=10)),
                ('mainpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.mainpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
