# Generated by Django 4.2.5 on 2023-09-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_mainpost_end_date_mainpost_price_mainpost_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpost",
            name="sentence",
            field=models.CharField(default="", max_length=30),
        ),
    ]
