# Generated by Django 4.2.5 on 2023-09-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_mainpost_sentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpost",
            name="sentence",
            field=models.CharField(max_length=30),
        ),
    ]
