# Generated by Django 4.2.5 on 2023-09-06 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_alter_mainpost_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpost",
            name="liked_users",
            field=models.ManyToManyField(
                related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
