# Generated by Django 4.2.5 on 2023-09-06 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_mainpost_liked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainreview",
            name="liked_users",
            field=models.ManyToManyField(
                related_name="liked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
