# Generated by Django 4.2.5 on 2023-09-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_mainreview_liked_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainreview",
            name="liked_users",
        ),
    ]
