# Generated by Django 4.2.5 on 2023-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_mainpost_liked_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpost",
            name="genre",
            field=models.CharField(
                choices=[
                    ("뮤지컬", "뮤지컬"),
                    ("연극", "연극"),
                    ("클래식", "클래식"),
                    ("무용", "무용"),
                    ("콘서트", "콘서트"),
                    ("가족", "가족"),
                ],
                default="뮤지컬",
                max_length=10,
            ),
        ),
    ]
