# Generated by Django 4.2.5 on 2023-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_mainreview_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mainpost_media/"),
        ),
    ]
