# Generated by Django 4.2.5 on 2023-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_mainpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mainpost_media"),
        ),
    ]
