# Generated by Django 4.2.4 on 2023-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('리허설', '리허설'), ('오버츄어', '오버츄어'), ('앙상블', '앙상블'), ('피날레', '피날레')], default='리허설', max_length=6),
        ),
    ]
