# Generated by Django 4.2.4 on 2023-09-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_customuser_nickname"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verification_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verification_code_expiry",
        ),
    ]
