# Generated by Django 4.2.5 on 2023-09-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
