# Generated by Django 4.2.4 on 2023-09-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_mainpost_liked_users'),
        ('user', '0013_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(related_name='likers', to='main.mainpost'),
        ),
    ]
